### ISSUE TITLE
[BUG] Confusing error message on aperture photometry tab when photutils is not installed

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#2546] opened 2023-11-01 20:48 UTC
### Jdaviz component

Imviz

### Description

I created a fresh environment to test something in jdaviz, but I forgot to install `photutils`.  Then when I tried to open up the aperture photometry plugin, I get the following rather misleading error:
![nodata_screenshot](https://github.com/spacetelescope/jdaviz/assets/346587/70213bb1-77c2-455d-9eab-bbbf512116ef)

The confusing thing being the "No data available", when, as the screenshot shows, there's clearly data.  If I re-do it with photutils installed it correctly shows the data sets present.

### How to Reproduce

1. Install jdaviz but *not* photutils
2. Start imviz, load some image
3. Open the aperture photometry plugin

### Expected behavior

I would have expected some sort of "photutils not installed" message in the plugin.

### Jupyter

IPython          : 8.16.0
ipykernel        : 6.25.2
ipywidgets       : 8.1.1
jupyter_client   : 7.0.6
jupyter_core     : 5.3.2
jupyter_server   : 1.24.0
jupyterlab       : 4.0.6
nbclient         : 0.8.0
nbconvert        : 7.8.0
nbformat         : 5.9.2
notebook         : 7.0.4
qtconsole        : 5.4.3
traitlets        : 5.10.1

### Software versions

Python 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.26.0
>>> import astropy; print("astropy", astropy.__version__)
astropy 5.3.1
>>> import matplotlib; print("matplotlib", matplotlib.__version__)
matplotlib 3.8.0
>>> import scipy; print("scipy", scipy.__version__)
scipy 1.11.3
>>> import skimage; print("scikit-image", skimage.__version__)
scikit-image 0.21.0
>>> import asdf; print("asdf", asdf.__version__)
asdf 2.15.0
>>> import stdatamodels; print("stdatamodels", stdatamodels.__version__)
stdatamodels 1.6.0
>>> import gwcs; print("gwcs", gwcs.__version__)
gwcs 0.18.3
>>> import regions; print("regions", regions.__version__)
regions 0.7
>>> import specutils; print("specutils", specutils.__version__)
specutils 1.11.0
>>> import specreduce; print("specreduce", specreduce.__version__)
specreduce 1.3.0
>>> import photutils; print("photutils", photutils.__version__)
photutils 1.8.0
>>> import astroquery; print("astroquery", astroquery.__version__)
astroquery 0.4.6
>>> import yaml; print("pyyaml", yaml.__version__)
pyyaml 6.0.1
>>> import asteval; print("asteval", asteval.__version__)
asteval 0.9.30
>>> import idna; print("idna", idna.__version__)
idna 3.4
>>> import traitlets; print("traitlets", traitlets.__version__)
traitlets 5.10.1
>>> import bqplot; print("bqplot", bqplot.__version__)
bqplot 0.12.39
>>> import bqplot_image_gl; print("bqplot-image-gl", bqplot_image_gl.__version__)
bqplot-image-gl 1.4.11
>>> import glue; print("glue-core", glue.__version__)
glue-core 1.12.0
>>> import glue_jupyter; print("glue-jupyter", glue_jupyter.__version__)
glue-jupyter 0.17.0
>>> import glue_astronomy; print("glue-astronomy", glue_astronomy.__version__)
glue-astronomy 0.10.0
>>> import echo; print("echo", echo.__version__)
echo 0.8.0
>>> import ipyvue; print("ipyvue", ipyvue.__version__)
ipyvue 1.9.2
>>> import ipyvuetify; print("ipyvuetify", ipyvuetify.__version__)
ipyvuetify 1.8.10
>>> import ipysplitpanes; print("ipysplitpanes", ipysplitpanes.__version__)
ipysplitpanes 0.2.0
>>> import ipygoldenlayout; print("ipygoldenlayout", ipygoldenlayout.__version__)
ipygoldenlayout 0.4.0
>>> import ipypopout; print("ipypopout", ipypopout.__version__)
ipypopout 1.0.0
>>> import jinja2; print("Jinja2", jinja2.__version__)
Jinja2 3.1.2
>>> import voila; print("voila", voila.__version__)
voila 0.4.1
>>> import vispy; print("vispy", vispy.__version__)
vispy 0.13.0
>>> import sidecar; print("sidecar", sidecar.__version__)
sidecar 0.5.2
>>> import jdaviz; print("Jdaviz", jdaviz.__version__)
Jdaviz 3.5.0
>>>

**Comment by pllim** [comment] 2023-11-01 21:24
How did you even get to the point of having jdaviz without photutils? photutils is a required dependency.

https://github.com/spacetelescope/jdaviz/blob/d03343962807e6eff39bd1834225e9eb7bf8608c/pyproject.toml#L28

Not sure if there is anything we can do to help you if you managed to circumvent pip install rules.

**Comment by pllim** [comment] 2023-11-01 21:25
Also your version manifest above says you have photutils 1.8.0

**Comment by kecnry** [comment] 2023-11-02 12:04
Aperture requires a _subset_ to exist.  We don't set the "No data available text", but I can see how that is very misleading, perhaps we can try to override it.  Or if there are no values, instead of showing the dropdown, show a warning alert in its place.

I don't think you can even import jdaviz without photutils, although we _could_ do what we do for footprints and allow importing and just disable the plugin (with a warning in the UI).

**Comment by pllim** [comment] 2023-11-02 14:10
I really don't think there is anything to fix here. It was likely user error. I asked Erik to close this issue if he cannot reproduce it.

**Closed** 2024-10-17 15:21 UTC
Labels: bug, imviz, needs-clarification
