### ISSUE TITLE
BUG: Imviz panning

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#534] opened 2021-04-15 16:02 UTC
Follow up of #429: *There is a bug with the panning which I am investigating.* -- @astrofrog

**Comment by astrofrog** [comment] 2021-04-15 16:37
I think the root cause is https://github.com/bqplot/bqplot/issues/1333

**Comment by pllim** [comment] 2021-04-15 17:55
Thanks for investigating! Should I re-assign to Maarten?

**Comment by astrofrog** [comment] 2021-04-15 18:29
Yes please!

**Comment by pllim** [comment] 2021-04-15 18:34
I cannot seem to do it officially, so pinging @maartenbreddels here instead.

**Comment by astrofrog** [comment] 2021-04-27 11:23
Looks like @maartenbreddels fixed this in https://github.com/bqplot/bqplot/pull/1339 - I will double check now that this resolves the jdaviz issues.

**Comment by astrofrog** [comment] 2021-04-27 11:36
Fixed in bqplot 0.12.26

**Closed** 2021-04-27 13:58 UTC
Labels: Upstream fix required, bug, imviz
