### ISSUE TITLE
specviz: exporting selected regions to SpectralRegion in notebook

### ISSUE THREAD

**Issue by skendrew** [spacetelescope/jdaviz#551] opened 2021-04-21 00:50 UTC
I am using specviz in a notebook and using it to select regions of my spectrum, and saving that to a SpectralRegion. When I select a single region, this works fine, but when I use the "add" feature to select multiple parts of the spectrum, then use regions = specviz.get_spectral_regions() to save to a SpectralRegion, this returns an error (see below). am I using this wrong?
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-3ab47ca4b999> in <module>
----> 1 regions = specviz.get_spectral_regions()
      2 print(regions)

~/anaconda3/envs/miricle/lib/python3.8/site-packages/jdaviz/configs/specviz/helper.py in get_spectral_regions(self)
     76             as `specutils.SpectralRegion` objects.
     77         """
---> 78         regions = self.app.get_subsets_from_viewer("spectrum-viewer")
     79 
     80         spec_regs = {}

~/anaconda3/envs/miricle/lib/python3.8/site-packages/jdaviz/app.py in get_subsets_from_viewer(self, viewer_reference, data_label)
    498                     #  the glue component objects
    499                     unit = value.data.coords.spectral_axis.unit
--> 500                     hi, lo = value.subset_state.hi, value.subset_state.lo
    501                     xcen = 0.5 * (lo + hi)
    502                     width = hi - lo

AttributeError: 'OrState' object has no attribute 'hi'
```

**Comment by pllim** [comment] 2021-04-21 14:57
Sounds like a bug, as `value.subset_state.hi` has an assumption that is not or no longer true.

**Comment by pllim** [comment] 2021-09-16 15:47
@camipacifici , so is this issue a duplicate of #356?

**Comment by camipacifici** [comment] 2021-09-16 16:04
I am pretty sure it is the same problem, but actually I am not sure if it has been fixed with all the changes that happened since April. I will give it a try as soon as the new release is out.

**Comment by pllim** [comment] 2021-09-16 16:07
In that case, I am closing this as duplicate. We can follow-up over at #356. Thanks!

**Closed by pllim** 2021-09-16 16:07 UTC
Labels: bug, duplicate, specviz
