### ISSUE TITLE
Layer menu does not work anymore in Lab split view

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#984] opened 2021-12-02 23:43 UTC
I saw this in Imviz but it is probably the same in other viz too. Pretty sure this used to work. Workflow to reproduce below.

1. Use dev version of Jdaviz.
2. Fire up Imviz example notebook.
3. Create new view for `imviz.app` and move it to the side.
4. Display some image.
5. Open the Layers menu.
6. When you try to click on anything in there, it disappears (non-functional).

![Screenshot 2021-12-02 184126](https://user-images.githubusercontent.com/2090236/144520282-d40ded81-d4f8-436c-bba1-8373e44b6761.jpg)

[🐱](https://jira.stsci.edu/browse/JDAT-2008)

**Comment by pllim** [comment] 2021-12-03 21:47
This bug is not in v2.0.0.

This bug is in `main` and also in Specviz, in addition to Imviz, so by extension, all the viz.

**Comment by pllim** [comment] 2021-12-03 21:55
Most likely introduced by #943 because going through the history, I started seeing it with 3dbc20f27038988c29e452cb759cdb0a23781ffe but not with 589bf69972bf3e244aa6f04d5e84c9e25ac18b86 .

**Comment by kecnry** [comment] 2021-12-06 14:27
@pllim - I can reproduce and see how it might be related to the "click away" logic on the menus.  My suspicion is that since there are two copies of the app, clicking in the menu of one is seen as clicking away in the other and so closing both copies of the menu.  The easiest solution would be to require closing the menu by clicking the icon (which would be consistent with the plotting toolbar), but we'll need to decide if that is acceptable behavior or not first.

**Comment by pllim** [comment] 2021-12-06 16:15
Whatever that fixes the bug would be acceptable for me. I am not picky. Getting it back to an usable state would be nice.

**Closed** 2022-12-01 18:27 UTC
Labels: bug, embed
