### ISSUE TITLE
[FEAT] Imviz: Default to having the top layer selected in the Layer Options plugin

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/jdaviz#1428] opened 2022-06-29 02:01 UTC
### Description

Right now the layer that is selected in the Layer Options plugin is just the last one that was selected, independent of whether you have blinked to another layer. I think it would be more intuitive to have the Layer Options shift to the top layer when you blink to another image, so that when you go to adjust the stretch in the plugin you are adjusting the right layer. 

### Additional context

I'm finding myself repeatedly adjusting the wrong image. Eventually I'm sure I'll learn to adjust to this behavior, but at least to me it's not intuitive.

**Comment by pllim** [comment] 2022-06-29 16:48
I think this is a duplicate of #743 , so closing as duplicate. Please move discussion to the other issue. Thanks!

**Closed by pllim** 2022-06-29 16:48 UTC
Labels: feature, imviz
