### ISSUE TITLE
jwst x1d data no longer loadable in specviz

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#390] opened 2021-01-13 21:29 UTC
When trying to load JWST x1d spectrum, I now get the following error when loading the data in SpecViz, `RuntimeError: Keyword SRCTYPE is None.  It should be 'POINT' or 'EXTENDED'. Can't decide between "flux" and "surf_bright" columns.
`

You can download a notebook for this data using the following url, http://dlarchcf1.stsci.edu:7000/viz/specviz?&filename=jw00736-o039_t001_miri_ch1-long_x1d.fits , and clicking "Open Data in Jupyter".  You may need to setup a MAST API token, at https://auth.mast.stsci.edu.  Or just ping me and I can share the data.

Full traceback
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-fd670cca78eb> in <module>
      1 output='/Users/bcherinka/.astropy/cache/download/url/10be1add87fe0b5d8cd18b1f55e7631d/contents'
----> 2 app.load_data(output)

~/Work/git/havok2063/jdaviz/jdaviz/app.py in load_data(self, file_obj, parser_reference, **kwargs)
    295             # If the parser returns something other than known, assume it's
    296             #  a message we want to make the user aware of.
--> 297             msg = parser(self, file_obj, **kwargs)
    298 
    299             if msg is not None:

~/Work/git/havok2063/jdaviz/jdaviz/configs/specviz/plugins/parsers.py in specviz_spectrum1d_parser(app, data, data_label, format, show_in_viewer)
     36 
     37         if path.is_file():
---> 38             data = Spectrum1D.read(str(path), format=format)
     39         else:
     40             raise FileNotFoundError("No such file: " + str(path))

~/anaconda3/envs/havokve/lib/python3.8/site-packages/astropy/nddata/mixins/ndio.py in __call__(self, *args, **kwargs)
     56 
     57     def __call__(self, *args, **kwargs):
---> 58         return registry.read(self._cls, *args, **kwargs)
     59 
     60 

~/anaconda3/envs/havokve/lib/python3.8/site-packages/astropy/io/registry.py in read(cls, format, cache, *args, **kwargs)
    518 
    519         reader = get_reader(format, cls)
--> 520         data = reader(*args, **kwargs)
    521 
    522         if not isinstance(data, cls):

~/Work/git/havok2063/specutils/specutils/io/default_loaders/jwst_reader.py in jwst_x1d_single_loader(file_obj, **kwargs)
     92         The spectrum contained in the file.
     93     """
---> 94     spectrum_list = _jwst_x1d_loader(file_obj, **kwargs)
     95     if len(spectrum_list) == 1:
     96         return spectrum_list[0]

~/Work/git/havok2063/specutils/specutils/io/default_loaders/jwst_reader.py in _jwst_x1d_loader(file_obj, **kwargs)
    166 
    167             else:
--> 168                 raise RuntimeError(f"Keyword SRCTYPE is {srctype}.  It should "
    169                                    "be 'POINT' or 'EXTENDED'. Can't decide between `flux` and "
    170                                    "`surf_bright` columns.")

RuntimeError: Keyword SRCTYPE is None.  It should be 'POINT' or 'EXTENDED'. Can't decide between `flux` and `surf_bright` columns.
```

**Comment by jdavies-st** [comment] 2021-01-15 20:59
SRCTYPE has been moved from the PRIMARY extension header to the SCI or EXTRACT1D extension header.  See:

https://github.com/spacetelescope/jwst/pull/4885

**Comment by havok2063** [comment] 2021-01-19 18:32
@jdavies-st ahh ok this explains things a bit.  I've been working with a few different files, ones recently ingested into the Portal, e.g. `jw00736-o039_t001_miri_ch1-long_x1d.fits`.  I do see the new `SRCTYAPT` header keyword, set to `UNKNOWN`, but there is no `SRCTYPE` keyword in either the `SCI` or `EXTRACT1D` extension headers.  This file has a calibration version of CAL_VER=0.17.1.  

We will need to update the JWST loaders in `specutils`, See https://github.com/astropy/specutils/blob/708f1eca3439de2ab953295a3b393ee0c57e7a96/specutils/io/default_loaders/jwst_reader.py#L154 .  Should these be updated to use the new `SRCTYAPT` keyword or continue to use the (moved) `SRCTYPE` keyword.  Reading the links, it looks like `SRCTYAPT` is the user-appointed source type, while `SRCTYPE` is the one actually used in the pipeline.  So I'm guessing we still want `specutils` to use `SRCTYPE`.

**Comment by havok2063** [comment] 2021-01-19 18:42
Same issue verified in `jw00668-o002_s00161_nirspec_f070lp-g140m_x1d.fits` which is also CAL_VER=0.17.1.

**Comment by jdavies-st** [comment] 2021-01-19 19:02
@hbushouse, any ideas how we could not have a SRCTYP keyword in the outputs?

**Comment by hbushouse** [comment] 2021-01-19 19:26
Given the complexities of different observing modes, instrument modes, and robustness of input data, it's generally impossible to answer questions of why the cal pipeline did or did not do something without actually looking at the various data products. From the data product names listed above, it appears the first is a MIRI MRS exposure, for which the default source type will be EXTENDED, unless SRCTYAPT was present and set to POINT. The second dataset is NIRSpec of some kind and given the high value of the `s00161` field in the file name (source id 161) I'm guess it's MOS mode. In this case SRCTYPE is set based on the value of STELLARITY assigned to this source in the MSA metadata file supplied by the user, which determines all of the slitlet and source parameters for the observation/exposure. It's possible that there wasn't a stellarity value given for this particular source, but I think in that case it should default to EXTENDED (the safest option).

So for either of these cases we would expect a SRCTYPE value to appear in the SCI or EXTRACT1D extension header of the output products, even if no suitable input value existed. So the fact that the keyword isn't there could indicate a bug that was present in 0.17.1, such as a bug involving the copying of meta data from the 2D or 3D products that are input to the extract_1d step to the output x1d products. Again, the only way to know for sure is to take a detailed look at the various input and output data products. And for the case of NIRSpec MOS, it's also necessary to look at the MSA metadata file.

**Comment by havok2063** [comment] 2021-01-20 14:35
@hbushouse @jdavies-st Shall I provide you with the data files so you can take a more detailed look?

**Comment by hbushouse** [comment] 2021-01-20 14:41
Yes, that would be helpful. What we'd really need is the rate file that goes into level-2b (calwebb_spec2) processing, which is what the source_type step operates on. And for the NIRSpec MOS exposure we'd also need the MSA metadata file (the name should be recorded in the MSAMETFL keyword).

**Comment by havok2063** [comment] 2021-01-20 17:17
@hbushouse Ok great.  I just sent you an email with some sample files.  Let me know if I didn't provide the right metadata files.

**Comment by ibusko** [comment] 2021-01-21 16:30
@havok2063 could you please share a file that generates this error?

**Comment by havok2063** [comment] 2021-01-21 17:39
@ibusko I just sent you an invite to access a relevant file.

**Comment by ibusko** [comment] 2021-01-21 19:46
Thanks, I can reproduce the error. It is generated by the JWST reader in `specutils`. I will file a github ticket and work in fixing this.

**Comment by ibusko** [comment] 2021-01-21 20:47
@havok2063 the test file has no SRCTYPE in the SCI header. I can only see a SRCTYAPT= 'UNKNOWN ' in the primary header. Which is useless since it has to be set to POINT or EXTENDED for the `specutils` reader to be able to read the file. 

maybe we need an entirely different logic here?

**Comment by hbushouse** [comment] 2021-01-21 20:58
The source_type step in the jwst cal pipeline should be determining a value for SRCTYPE when SRCTYAPT='UNKNOWN'. We (the jwst cal pipeline folks) just need to get our hands on the data files to try to figure out why that didn't happen in these cases. And there's no one universal answer as to why, because the logic for determining SRCTYPE is dependent on the observing mode.

**Comment by drlaw1558** [comment] 2021-01-21 22:05
@havok2063 Can you ping me a link to the data as well (as far back to the original pipeline input files as possible)?  Since it's MRS data I'd be curious to take a look.

**Comment by havok2063** [comment] 2021-01-21 22:25
@drlaw1558 sure I'll email you a link of some sample files with some additional instructions on to recover additional ones if need be.  I just happened across this issue almost randomly since the `specutils` JWST data loaders for x1d spectra utilize the `SRCTYPE` keyword and the test files I use in MAST all of sudden stopped loading in SpecViz.  Who knows where else this could be affected.

**Comment by drlaw1558** [comment] 2021-01-22 00:26
Reprocessing one of the example _rate.fits files through spec2 it looks like it is properly populating SRCTYPE in the SCI header of the _cal.fits files (SRCTYPE = EXTENDED, in this case).  That flows down properly to the _s3d.fits data cubes and is being picked up by the 1d spectral extraction code correctly to determine the details of how to perform spectral extraction.

It looks like the information is being lost when extract1d writes out the _x1d.fits files, as I don't see the keyword in the header any longer at that point.  More generally, something seems funny about the _x1d.fits extensions.  I believe these files are meant to have a 0th extension, a 1st extension (EXTRACT1D), and a second extension (ASDF), but they actually have more: 0th, SCI, EXTRACT1D, and ASDF.  All of the useful spectra are in the EXTRACT1D extension; SCI has no data and only a few header keywords.  I wonder if this is confusing the data model trying to write out some information such as SRCTYPE?

**Comment by havok2063** [comment] 2021-01-22 15:32
Ahh that's interesting.  Yeah I noticed the new SCI extension in the x1d files which seemed out of place, and not in agreement with the documented data model.  That issue has been around for a while.  I first noticed it back in September, and filed an issue here, https://github.com/astropy/specutils/pull/715.  Following the link in that thread, it looks like that bug is still an open issue.

**Comment by hbushouse** [comment] 2021-01-22 15:41
Yes, the errant SCI extension in x1d products is on our bug list to get fixed. It's due to an issue with the internals of our datamodels and is included when the file gets created (by astropy.io.fits) simply because there's one or more keyword values populated in the datamodel that reside in the SCI extension. So the extension gets created just to store that keyword, and nothing else!  You'll notice that there's only a header for the SCI HDU - no data array. So it's just a bogus extra extension that can be ignored.

Regarding the ASDF extension, that's standard for all data products and contains all of the meta attributes of the datamodel (keywords, WCS objects, etc.) stored in ASDF format.

We actually have another JP ticket open to consider renaming the EXTRACT1D and COMBINE1D extensions that currently exist in x1d and c1d products to use the standard "SCI" extension name, just like all other data products. That would create consistency across all the types of data products and would also solve the issue above regarding the blank SCI extension that currently appears. Of course such a change would need to be coordinated with lots of other groups - such as this one - who have code that currently depends on the "EXTRACT1D" extension name. So just a heads up that that might be coming.

**Comment by hbushouse** [comment] 2021-01-26 20:41
Brian sent me a couple of example datasets, one MIRI MRS and one NIRSpec MOS. Using the latest B7.7 version of the Cal pipeline, SRCTYPE propagates into the "cal", "s2d", and "s3d" products properly, and also into the "x1d" product for the NIRSpec MOS case. But it does NOT get populated in the "x1d" product for the MIRI MRS example. Browsing the code suggests that the dedicated module within the extract_1d step that's used for IFU data (MIRI MRS and NIRSpec IFU) is not copying that keyword to the x1d output. In fact going back several versions of the code I don't see that it ever was!

I've filed ticket https://jira.stsci.edu/browse/JP-1880 to get this fixed.

**Comment by ibusko** [comment] 2021-01-27 14:38
I verified that, by manually adding the SRCTYPE keyword to a header, the x1d files load correctly. We just have to know in which extension header it goes. So this issue should be marked as blocked by https://jira.stsci.edu/browse/JP-1880

**Comment by hbushouse** [comment] 2021-01-27 14:44
For x1d products the SRCTYPE keyword should always appear in the "EXTRACT1D" extension header. Upstream products, such as "s2d", "s3d", "cal" (which are all higher dimensionality, i.e. 2-D or 3-D data) it appears in the "SCI" extension header.

**Comment by hbushouse** [comment] 2021-02-01 15:54
Propagation of SRCTYPE keyword to x1d products fixed in Cal pipeline code by https://github.com/spacetelescope/jwst/pull/5685

**Comment by havok2063** [comment] 2021-02-01 16:28
Great!  Any idea when this change will propagate into some test data we could use.  Or even what pipeline build this change will be a part of?

**Comment by hbushouse** [comment] 2021-02-01 16:31
Unfortunately the change did not make it into our B7.7 delivery, which got closed to new work about a week ago. So the next formal release that would include it is the B7.7.1 that's due around the beginning of March.

In the meantime we'll start making DMS test runs on the current dev code (which includes the fix) sometime in the next couple weeks and so we could make some of those results available to you.

**Comment by havok2063** [comment] 2021-02-01 18:40
Ok sounds good.  Yeah, once some test data is available it would be great to have access to it.

**Comment by havok2063** [comment] 2022-06-06 18:45
Yeah I think this is resolved and can be closed.

**Closed** 2022-06-06 19:46 UTC
Labels: specviz
