### ISSUE TITLE
Default opacity in Imviz should be 1

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/jdaviz#537] opened 2021-04-15 16:24 UTC
Currently (because of defaults in glue) image layers have a default opacity of 0.8 - we should change this to default to 1.

**Comment by pllim** [comment] 2021-04-15 16:25
Is this a duplicate of #535 ?

**Comment by astrofrog** [comment] 2021-04-15 16:37
I *think* so but not sure, I want to fix this first and see if it explained #535

**Closed** 2021-04-27 14:21 UTC
Labels: bug, imviz
