### ISSUE TITLE
[BUG] Cubeviz: partial spectrum plot on extreme zoom

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#1177] opened 2022-03-18 13:45 UTC
**Describe the bug**
After zooming in by a factor of 10^7 or so on a spectrum with large noise spikes, the bottom half of the plotted spectrum
disappears.  This happens both with box zoom and vertical zoom widgets in the Cubeviz spectrum viewer.

**To Reproduce**
1. Launch Cubeviz app in Jupyter notebook 
2. load Spectrum1D cube into cubeviz from notebook cell
3. Use vertical zoom or box zoom to zoom in multiple times to achieve a zoom factor of about 10^7
4. Bottom half of spectrum suddenly disappears from plot. 
5. Unzooming makes the spectrum reappear

**Expected behavior**
Should be able to zoom this much and even more without the spectrum disappearing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX 10.15.7
 - Browser: Firefox
 - Jupyter: [run "jupyter --version"]
 jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.4
ipython          : 7.14.0
ipykernel        : 5.3.0
jupyter client   : 6.1.11
jupyter lab      : 3.2.9
nbconvert        : 6.0.7
ipywidgets       : 7.6.5
nbformat         : 5.0.6
traitlets        : 5.0.5

**Package versions (please complete the following information):**

macOS-10.15.7-x86_64-i386-64bit
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27) 
[Clang 9.0.1 ]
Numpy 1.20.3
astropy 4.3.1
specutils 1.7.0
pyyaml 5.4.1
click 7.1.2
asteval 0.9.23
idna 2.10
traitlets 5.0.5
bqplot 0.12.33
bqplot-image-gl 1.4.5
glue-core 1.2.2
glue-jupyter 0.10.1
glue-astronomy 0.3.2
echo 0.5
ipyvue 1.7.0
ipyvuetify 1.8.1
ipysplitpanes 0.1.0
ipygoldenlayout 0.3.0
voila 0.2.6
vispy 0.6.6
Jdaviz 2.3.0

**Additional context (e.g. data files)**
This is a JWST datacube read in as a Spectrum1D

[🐱](https://jira.stsci.edu/browse/JDAT-2248)

**Comment by maartenbreddels** [comment] 2022-04-19 15:07
Since we now moved to using webgl https://github.com/glue-viz/glue-jupyter/pull/227 for the spectral viewer, I'd like to get 
a confirmation that the bug is still present.

I think it is, if I zoom in and the x-range is 6.760833355380799e, 7-6.7608331907412e-7 (delta is 1.646395991967872e-14, which is a relative delta of 2.4e-8) the line disappears.

The issue occurs (at least in the WebGL version) I think because of float32 precision. The relative delta is so small, that it is probably 0 on the GPU. I can see if we can use a different way of doing the calculations on the GPU such that we don't hit this issue (if this is confirmed to still be a bug)

**Comment by pllim** [comment] 2022-05-10 14:33
According to update from Maarten offline, we need to update the pin to `bqplot-image-gl>=1.4.8` and close this out.

**Comment by pllim** [comment] 2022-05-10 20:35
Update: bqplot-image-gl 1.4.8 had packaging problem, so now we need to do `bqplot-image-gl>=1.4.9`

**Closed** 2022-05-11 13:38 UTC
Labels: bug, cubeviz, Upstream fix required
