### ISSUE TITLE
[BUG] Specviz: Line analysis does not work on two subsets using API

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#1279] opened 2022-04-29 17:20 UTC
**Describe the bug**
A test in #1275 exposed a bug where if the continuum subset is set to subset 1 and spectral subset is set to subset 2, a traceback is returned.

<details>

```
        plugin.spectral_subset_selected = 'Subset 2'
>       plugin.continuum_subset_selected = 'Subset 1'

test_line_analysis.py:263: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Users/javerbukh/opt/anaconda3/envs/jdaviz-dev-2.5/lib/python3.8/site-packages/traitlets/traitlets.py:606: in __set__
    self.set(obj, value)
/Users/javerbukh/opt/anaconda3/envs/jdaviz-dev-2.5/lib/python3.8/site-packages/traitlets/traitlets.py:595: in set
    obj._notify_trait(self.name, old_value, new_value)
/Users/javerbukh/opt/anaconda3/envs/jdaviz-dev-2.5/lib/python3.8/site-packages/traitlets/traitlets.py:1219: in _notify_trait
    self.notify_change(Bunch(
/Users/javerbukh/opt/anaconda3/envs/jdaviz-dev-2.5/lib/python3.8/site-packages/ipywidgets/widgets/widget.py:686: in notify_change
    super(Widget, self).notify_change(change)
/Users/javerbukh/opt/anaconda3/envs/jdaviz-dev-2.5/lib/python3.8/site-packages/traitlets/traitlets.py:1229: in notify_change
    return self._notify_observers(change)
/Users/javerbukh/opt/anaconda3/envs/jdaviz-dev-2.5/lib/python3.8/site-packages/traitlets/traitlets.py:1266: in _notify_observers
    c(event)
../line_analysis.py:275: in _calculate_statistics
    right_max = np.nanmax([np.nanmax(mark_x['right']), sr.upper.value])
<__array_function__ internals>:180: in nanmax
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

a = array([nan, nan]), axis = None, out = None, keepdims = <no value>, initial = <no value>, where = <no value>

    @array_function_dispatch(_nanmax_dispatcher)
    def nanmax(a, axis=None, out=None, keepdims=np._NoValue, initial=np._NoValue,
               where=np._NoValue):
        """
        Return the maximum of an array or maximum along an axis, ignoring any
        NaNs.  When all-NaN slices are encountered a ``RuntimeWarning`` is
        raised and NaN is returned for that slice.
    
        Parameters
        ----------
        a : array_like
            Array containing numbers whose maximum is desired. If `a` is not an
            array, a conversion is attempted.
        axis : {int, tuple of int, None}, optional
            Axis or axes along which the maximum is computed. The default is to compute
            the maximum of the flattened array.
        out : ndarray, optional
            Alternate output array in which to place the result.  The default
            is ``None``; if provided, it must have the same shape as the
            expected output, but the type will be cast if necessary. See
            :ref:`ufuncs-output-type` for more details.
    
            .. versionadded:: 1.8.0
        keepdims : bool, optional
            If this is set to True, the axes which are reduced are left
            in the result as dimensions with size one. With this option,
            the result will broadcast correctly against the original `a`.
    
            If the value is anything but the default, then
            `keepdims` will be passed through to the `max` method
            of sub-classes of `ndarray`.  If the sub-classes methods
            does not implement `keepdims` any exceptions will be raised.
    
            .. versionadded:: 1.8.0
        initial : scalar, optional
            The minimum value of an output element. Must be present to allow
            computation on empty slice. See `~numpy.ufunc.reduce` for details.
    
            .. versionadded:: 1.22.0
        where : array_like of bool, optional
            Elements to compare for the maximum. See `~numpy.ufunc.reduce`
            for details.
    
            .. versionadded:: 1.22.0
    
        Returns
        -------
        nanmax : ndarray
            An array with the same shape as `a`, with the specified axis removed.
            If `a` is a 0-d array, or if axis is None, an ndarray scalar is
            returned.  The same dtype as `a` is returned.
    
        See Also
        --------
        nanmin :
            The minimum value of an array along a given axis, ignoring any NaNs.
        amax :
            The maximum value of an array along a given axis, propagating any NaNs.
        fmax :
            Element-wise maximum of two arrays, ignoring any NaNs.
        maximum :
            Element-wise maximum of two arrays, propagating any NaNs.
        isnan :
            Shows which elements are Not a Number (NaN).
        isfinite:
            Shows which elements are neither NaN nor infinity.
    
        amin, fmin, minimum
    
        Notes
        -----
        NumPy uses the IEEE Standard for Binary Floating-Point for Arithmetic
        (IEEE 754). This means that Not a Number is not equivalent to infinity.
        Positive infinity is treated as a very large number and negative
        infinity is treated as a very small (i.e. negative) number.
    
        If the input has a integer type the function is equivalent to np.max.
    
        Examples
        --------
        >>> a = np.array([[1, 2], [3, np.nan]])
        >>> np.nanmax(a)
        3.0
        >>> np.nanmax(a, axis=0)
        array([3.,  2.])
        >>> np.nanmax(a, axis=1)
        array([2.,  3.])
    
        When positive infinity and negative infinity are present:
    
        >>> np.nanmax([1, 2, np.nan, np.NINF])
        2.0
        >>> np.nanmax([1, 2, np.nan, np.inf])
        inf
    
        """
        kwargs = {}
        if keepdims is not np._NoValue:
            kwargs['keepdims'] = keepdims
        if initial is not np._NoValue:
            kwargs['initial'] = initial
        if where is not np._NoValue:
            kwargs['where'] = where
    
        if type(a) is np.ndarray and a.dtype != np.object_:
            # Fast, but not safe for subclasses of ndarray, or object arrays,
            # which do not implement isnan (gh-9009), or fmax correctly (gh-8975)
            res = np.fmax.reduce(a, axis=axis, out=out, **kwargs)
            if np.isnan(res).any():
>               warnings.warn("All-NaN slice encountered", RuntimeWarning,
                              stacklevel=3)
E               RuntimeWarning: All-NaN slice encountered


```

</details>

**To Reproduce**
1. Go to `test_line_analysis`
2. Uncomment the line after the `#TODO` statement
3. Run `pytest -s .` from within the line analysis tests directory

**Comment by pllim** [comment] 2022-04-29 21:27
It is actually just a warning but we convert all unhandled warnings into exceptions in the test suite.

The question is how to properly handle this warning? Perhaps this has been discussed in my absence, so please post any relevant decisions here for future reference.

This is what throwing the warning:

```python
right_max = np.nanmax([np.nanmax(mark_x['right']), sr.upper.value])
```

This is because the input is `array([nan, nan])`. Is this expected? If so, we can ignore the warning. If not, then it is a bug.

**Comment by kecnry** [comment] 2022-04-30 00:25
So long as its the inner `nanmax` that is triggering the warning, then `right_max` should resolve to `sr.upper.value`, as designed. 
 So I think it should be safe to ignore the warning (if `sr.upper.value` were also `Nan` then we'd have problems in many places).

**Comment by pllim** [comment] 2022-04-30 13:03
I am unable to reproduce this error locally when I run the test code in an interactive notebook.

Currently, I am unable to run pytest locally for other reasons. But unless you are in a big rush, I would recommend spend one more day debugging this over at #1275 .

* For instance, what about swapping the Subset access? Currently, you access Subset 2 first before 1. Just swap the two lines and see.
* Or try printing out the internal plugin variable that is causing error and then backtrace the logic to see what is really going on. You can see the print outputs before the traceback starts. Usually I prepend some asterisks to make them stand out.

**Comment by pllim** [comment] 2022-04-30 23:23
OK, I did manage to run the test locally after a trip to Mordor. I pushed a fixed for the test mentioned here directly to #1275 and rebased it. I hope you don't mind. Please review it.

**Closed** 2022-05-02 11:05 UTC
Labels: bug, specviz
